# 公共配置文件
spring:
  application:
    name: talk-project
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 默认 dev 环境
#  profiles:
#    active: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/talk-project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 11111111
  redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    timeout: 3000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
upload:
  filePath: F:\\temp\\upload\\
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
llm:
#  阿里 通义千问apiKey
  tyqw:
    apiKey: your api key